Repository ScilifelabDataCentre/dds_web, pull requests merged in 2021-09, with the labels that each got.

#528 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: help wanted

#579 Remove project auth endpoint, Hand the project to apis3connector and …
  dds_web/api/__init__.py
  dds_web/api/api_s3_connector.py
  dds_web/api/db_connector.py
  dds_web/api/dds_decorators.py
  dds_web/api/errors.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/api/s3.py
  dds_web/api/user.py
  dds_web/development/db_init.py
  dds_web/security/auth.py
  dds_web/utils.py
Labels: Epic 6

#598 Er diagram alterations
  dds_web/api/db_connector.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/api/user.py
  dds_web/database/models.py
  dds_web/development/db_init.py
  dds_web/utils.py
  tests/conftest.py
Labels: backend, database, should have
