Repository ScilifelabDataCentre/dds_web, pull requests merged in 2021-12, with the labels that each got.

#722 Password reset
  dds_web/api/schemas/user_schemas.py
  dds_web/database/models.py
  dds_web/forms.py
  dds_web/templates/index.html
  dds_web/templates/user/login.html
  dds_web/templates/user/request_reset_password.html
  dds_web/templates/user/reset_password.html
  dds_web/utils.py
  dds_web/web/user.py
Labels: must have, Epic 9

#726 Fix foreign key constraints
  dds_web/database/models.py
Labels: database, must have

#734 project.current_status instead of just current_status
  dds_web/api/files.py
Labels: bug, must have

#733 Factories to create larger test datasets
  .env
  dds_web/__init__.py
  dds_web/development/factories.py
  docker-compose.yml
  requirements.txt
Labels: backend, database, should have

#736 small error, should not be not
  dds_web/database/models.py
Labels: bug

#732 Remove expiredfiles
  dds_web/database/models.py
  dds_web/utils.py
Labels: backend, database, must have

#737 Mock for boto3
  tests/conftest.py
  tests/test_project_creation.py
  tests/test_project_status.py
Labels: tests
