Repository ScilifelabDataCentre/dds_web, pull requests merged in 2021-11, with the labels that each got.

#670 Update code to reflect previous refactoring
  dds_web/api/project.py
  dds_web/api/user.py
  tests/test_project_creation.py
  tests/test_user_add.py
Labels: backend

#669 Move marshmallows to schema folder
  dds_web/api/api_s3_connector.py
  dds_web/api/db_connector.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/api/s3.py
  dds_web/api/schemas/__init__.py
  dds_web/api/schemas/custom_fields.py
  dds_web/api/schemas/file_schemas.py
  dds_web/api/schemas/project_schemas.py
  dds_web/api/schemas/user_schemas.py
  dds_web/api/user.py
  dds_web/utils.py
Labels: backend

#672 Remove `Project.size`
  dds_web/api/__init__.py
  dds_web/api/db_connector.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/database/models.py
  dds_web/development/db_init.py
  tests/__init__.py
  tests/conftest.py
  tests/test_project_creation.py
Labels: enhancement, backend, database

#704 Move verify password
  dds_web/api/schemas/user_schemas.py
  dds_web/api/user.py
  dds_web/database/models.py
  dds_web/development/db_init.py
  dds_web/forms.py
  dds_web/security/auth.py
  dds_web/utils.py
  tests/conftest.py
Labels: must have, Epic 9

#709 removed suffix line
  dds_web/utils.py
Labels: bug

#717 First step in creating a project status framework
  dds_web/api/__init__.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/database/models.py
  dds_web/development/db_init.py
  tests/__init__.py
  tests/conftest.py
  tests/test_files_new.py
  tests/test_project_creation.py
  tests/test_project_status.py
Labels: Epic 2, Epic 4, must have
