Repository ScilifelabDataCentre/dds_web, pull requests merged in 2021-10, with the labels that each got.

#608 Fix scheduler issue with Johannes
  dds_web/utils.py
Labels: backend, must have

#606 Add create_proj api endpoint
  dds_web/api/__init__.py
  dds_web/api/project.py
  dds_web/crypt/key_gen.py
  dds_web/database/models.py
  dds_web/development/db_init.py
Labels: backend, must have

#614 Small touches to the code related to roles.
  dds_web/api/project.py
  dds_web/security/auth.py
Labels: Epic 6

#621 fixed decryption error
  dds_web/api/files.py
  dds_web/database/models.py
  dds_web/development/db_init.py
Labels: bug, cryptography, database

#626 Implement Unittests for API calls (Issue #602)
  dds_web/api/errors.py
  dds_web/api/marshmallows.py
  tests/__init__.py
  tests/conftest.py
  tests/requirements-test.txt
  tests/test_basic_api.py
  tests/test_files.py
  tests/test_project_creation.py
  tests/test_project_listing.py
Labels: tests, Epic 9
