Repository ScilifelabDataCentre/dds_web, pull requests merged in 2022-02, with the labels that each got.

#806 create new project with temporary keys etc
  dds_web/api/schemas/project_schemas.py
Labels: must have

#843 Badges
  README.md
Labels: documentation, tests

#856 Change in project ID
  dds_web/api/schemas/project_schemas.py
Labels: must have

#867 added -y
  Dockerfiles/backend.Dockerfile
Labels: bug, must have

#865 Add tests for file upload
  tests/test_files_new.py
Labels: tests

#871 changelog added
  CHANGELOG.md
Labels: documentation

#881 Add docstrings
  dds_web/api/schemas/custom_fields.py
  dds_web/api/schemas/file_schemas.py
  dds_web/security/auth.py
  dds_web/security/project_user_keys.py
  dds_web/utils.py
Labels: documentation

#888 Issue860 invites multiple projects
  CHANGELOG.md
  dds_web/api/project.py
  dds_web/api/schemas/user_schemas.py
  dds_web/api/user.py
  dds_web/database/models.py
  tests/conftest.py
  tests/test_project_creation.py
  tests/test_user_add.py
Labels: must have

#900 Web tests, login, change password
  CHANGELOG.md
  tests/__init__.py
  tests/test_login_web.py
  tests/test_user_change_password.py
Labels: tests, should have

#885 ProjectAccess endpoint
  CHANGELOG.md
  dds_web/api/__init__.py
  dds_web/api/dds_decorators.py
  dds_web/api/project.py
  dds_web/security/auth.py
  dds_web/utils.py
  tests/__init__.py
  tests/test_project_access.py
Labels: must have

#886 Reactivate project access
  dds_web/api/dds_decorators.py
  dds_web/api/project.py
  dds_web/api/user.py
  tests/test_user_activation.py
Labels: must have

#903 Add isactive check to reset
  CHANGELOG.md
  dds_web/web/user.py
  tests/test_user_reset_password.py
Labels: must have

#890 Database migrations
  .github/pull_request_template.md
  CHANGELOG.md
  Dockerfiles/backend.Dockerfile
  README.md
  dds_web/__init__.py
  docker-compose.yml
  migrations/README
  migrations/alembic.ini
  migrations/env.py
  migrations/script.py.mako
  migrations/versions/e5a51e5ed9a1_initial.py
  requirements.txt
  tests/conftest.py
  tests/docker-compose-test.yml
Labels: database, NeededForStable, must have

#906 Ignore development folder
  codecov.yml
Labels: tests

#911 Invite researchers to projects
  CHANGELOG.md
  dds_web/api/project.py
  dds_web/api/schemas/user_schemas.py
  dds_web/api/user.py
  dds_web/database/models.py
  dds_web/errors.py
  dds_web/security/project_user_keys.py
  dds_web/utils.py
  migrations/versions/d117e6299dc9_remove_project_invites.py
  tests/test_basic_api.py
  tests/test_flow_invite_to_access.py
  tests/test_user_add.py
  tests/test_user_confirm_invites_and_register.py
  tests/test_user_delete.py
Labels: must have

#913 Change non sensitive
  CHANGELOG.md
  dds_web/api/project.py
  dds_web/api/schemas/project_schemas.py
  dds_web/database/models.py
  migrations/versions/a5a40d843415_changed_sensitive.py
  tests/test_project_creation.py
Labels: should have

#918 Add tests for download endpoints
  dds_web/errors.py
  tests/test_files_download.py
  tests/test_files_new.py
Labels: tests

#925 Fix empty requests
  dds_web/api/dds_decorators.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/api/s3.py
  dds_web/api/schemas/file_schemas.py
  dds_web/api/schemas/project_schemas.py
  dds_web/api/schemas/token_schemas.py
  dds_web/api/schemas/user_schemas.py
  dds_web/api/user.py
  dds_web/errors.py
  tests/test_bad_requests.py
  tests/test_basic_api.py
  tests/test_files_download.py
  tests/test_files_new.py
  tests/test_project_access.py
  tests/test_project_creation.py
  tests/test_project_listing.py
  tests/test_project_status.py
  tests/test_project_user_keys.py
  tests/test_user_activation.py
  tests/test_user_add.py
  tests/test_user_delete.py
  tests/test_user_remove_association.py
Labels: tests, must have

#935 create new superadmin
  dds_web/__init__.py
  dds_web/config.py
  dds_web/database/models.py
  dds_web/web/user.py
  migrations/versions/666003748d14_change_active_nullable_and_default.py
Labels: must have

#938 fix for creating unit admin
  CHANGELOG.md
  dds_web/api/schemas/project_schemas.py
  dds_web/api/user.py
  dds_web/development/db_init.py
Labels: must have

#940 Bug fixes and Super admin to add unit admins
  CHANGELOG.md
  dds_web/api/schemas/project_schemas.py
  dds_web/api/user.py
  dds_web/development/db_init.py
Labels: must have

#942 Add an ADR-ish (Architecture Decision Record)
  ADR.md
  README.md
  docker-compose.yml
  img/zstandard.png
Labels: documentation

#941 add link to pdf
  dds_web/templates/user/login.html
  docker-compose.yml
Labels: documentation
