Repository ScilifelabDataCentre/dds_web, pull requests merged in 2022-04, with the labels that each got.

#1082 Prep before production
  .gitpod.yml
  .vscode/settings.json
  ADR.md
  CHANGELOG.md
  dds_web/__init__.py
  dds_web/api/__init__.py
  dds_web/api/api_s3_connector.py
  dds_web/api/db_tools.py
  dds_web/api/dds_decorators.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/api/s3.py
  dds_web/api/schemas/file_schemas.py
  dds_web/api/schemas/project_schemas.py
  dds_web/api/unit.py
  dds_web/api/user.py
  dds_web/database/models.py
  dds_web/development/db_init.py
  dds_web/development/factories.py
  dds_web/errors.py
  dds_web/forms.py
  dds_web/run_app.py
  dds_web/scheduled_tasks.py
  dds_web/security/auth.py
  dds_web/security/project_user_keys.py
  dds_web/security/tokens.py
  dds_web/static/package-lock.json
  dds_web/templates/error.html
  dds_web/templates/home.html
  dds_web/templates/mail/authenticate.html
  dds_web/templates/mail/project_access_reset.html
  dds_web/templates/mail/project_access_reset.txt
  dds_web/templates/navbar.html
  dds_web/templates/user/account.html
  dds_web/templates/user/change_password.html
  dds_web/templates/user/confirm2fa.html
  dds_web/templates/user/logout.html
  dds_web/templates/user/password_reset_completed.html
  dds_web/templates/user/projects.html
  dds_web/templates/user/request_reset_password.html
  dds_web/templates/user/reset_password.html
  dds_web/utils.py
  dds_web/web/user.py
  docker-compose.yml
  migrations/versions/1256117ad629_add_password_reset.py
  migrations/versions/666003748d14_change_active_nullable_and_default.py
  migrations/versions/a5a40d843415_changed_sensitive.py
  migrations/versions/d117e6299dc9_remove_project_invites.py
  requirements.txt
  tests/__init__.py
  tests/test_project_creation.py
  tests/test_project_status.py
  tests/test_token.py
  tests/test_unit_list.py
  tests/test_user_add.py
  tests/test_user_delete.py
  tests/test_user_remove_association.py
  tests/test_user_reset_password.py
  tests/test_users_list.py
Labels: must have

#1122 Change default sender to a tuple to show that you can also set a name
  dds_web/config.py
Labels: should have

#1121 Front-end styling for registration page
  dds_web/forms.py
  dds_web/templates/components/login_form.html
  dds_web/templates/user/change_password.html
  dds_web/templates/user/confirm2fa.html
  dds_web/templates/user/register.html
  dds_web/templates/user/request_reset_password.html
  dds_web/templates/user/reset_password.html
  dds_web/templates/user/userexists.html
Labels: should have

#1126 Changelog for cronjob
  CHANGELOG.md
Labels: documentation

#1127 Add required argument for custom error
  dds_web/api/project.py
Labels: bug, must have

#1124 Identify and delete lost files
  CHANGELOG.md
  dds_web/__init__.py
Labels: backend, must have

#1115 Add scheduled job to archive projects
  CHANGELOG.md
  dds_web/scheduled_tasks.py
Labels: backend, must have

#1131 make ADR a doc
  ADR.docx
Labels: documentation

#1133 remove wrong info about facilities
  dds_web/templates/home.html
Labels: documentation, web-interface, must have

#1130 Add the SciLifeLab logo to the navbar
  dds_web/static/img/scilifelab_logo.svg
  dds_web/static/img/scilifelab_logo_darkbg.svg
  dds_web/static/package.json
  dds_web/static/scss/_custom.scss
  dds_web/static/scss/_variables.scss
  dds_web/static/scss/dds_dark.scss
  dds_web/static/scss/dds_light.scss
  dds_web/templates/base.html
  dds_web/templates/components/navbar.html
Labels: web-interface, must have

#1143 Publish to GHCR as well
  .github/workflows/dockerhub.yml
Labels: should have

#1145 Fix image build
  .github/workflows/dockerhub.yml
Labels: must have

#1146 Clarify error messages when incorrect field input e.g. email
  CHANGELOG.md
  dds_web/api/project.py
  dds_web/api/schemas/project_schemas.py
Labels: should have

#1148 New logos
  CHANGELOG.md
  dds_web/static/img/dds_logo_dark_bg.svg
  dds_web/static/img/dds_logo_light_bg.svg
  dds_web/static/img/scilifelab_symbol.svg
  dds_web/static/img/sll_logo_dark_bg.svg
  dds_web/static/img/sll_logo_light_bg.svg
  dds_web/static/package.json
  dds_web/templates/base.html
  dds_web/templates/components/login_form.html
  dds_web/templates/components/navbar.html
  dds_web/templates/home.html
  tests/__init__.py
Labels: web-interface, must have

#1151 Policy
  CHANGELOG.md
  dds_web/forms.py
  dds_web/templates/policy.html
  dds_web/templates/user/register.html
  dds_web/web/root.py
  tests/test_flow_invite_to_access.py
  tests/test_user_confirm_invites_and_register.py
Labels: documentation, must have

#1147 Delete Invite
  CHANGELOG.md
  dds_web/database/models.py
  dds_web/scheduled_tasks.py
  migrations/versions/1fbd604872e9_add_column_created_at.py
  tests/conftest.py
  tests/test_scheduled_tasks.py
Labels: backend, must have

#1152 Empty returned
  dds_web/api/user.py
Labels: bug, must have

#1153 Invite bug: Check for if the unit has any projects
  dds_web/api/user.py
Labels: bug, must have

#1154 Bug: Checks for invalid characters when creating unit
  CHANGELOG.md
  dds_web/__init__.py
  dds_web/database/models.py
  migrations/env.py
  migrations/versions/1ab892d08e16_change_public_id_length.py
Labels: bug, backend, must have

#1155 remove 'currently minimal'
  dds_web/templates/home.html
Labels: documentation, should have

#1150 Before release 1.0.1
  .github/workflows/dockerhub.yml
  ADR.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  dds_web/__init__.py
  dds_web/api/__init__.py
  dds_web/api/project.py
  dds_web/api/schemas/project_schemas.py
  dds_web/api/unit.py
  dds_web/api/user.py
  dds_web/config.py
  dds_web/database/models.py
  dds_web/development/db_init.py
  dds_web/forms.py
  dds_web/scheduled_tasks.py
  dds_web/static/img/dds_logo_dark_bg.svg
  dds_web/static/img/dds_logo_light_bg.svg
  dds_web/static/img/scilifelab_logo.svg
  dds_web/static/img/scilifelab_logo_darkbg.svg
  dds_web/static/img/scilifelab_symbol.svg
  dds_web/static/img/sll_logo_dark_bg.svg
  dds_web/static/img/sll_logo_light_bg.svg
  dds_web/static/package.json
  dds_web/static/scss/_custom.scss
  dds_web/static/scss/_variables.scss
  dds_web/static/scss/dds_dark.scss
  dds_web/static/scss/dds_light.scss
  dds_web/templates/base.html
  dds_web/templates/components/login_form.html
  dds_web/templates/components/navbar.html
  dds_web/templates/home.html
  dds_web/templates/policy.html
  dds_web/templates/user/change_password.html
  dds_web/templates/user/confirm2fa.html
  dds_web/templates/user/register.html
  dds_web/templates/user/request_reset_password.html
  dds_web/templates/user/reset_password.html
  dds_web/templates/user/userexists.html
  dds_web/web/root.py
  migrations/env.py
  migrations/versions/19b877061c98_add_motd.py
  migrations/versions/1ab892d08e16_change_public_id_length.py
  migrations/versions/1fbd604872e9_add_column_created_at.py
  tests/__init__.py
  tests/conftest.py
  tests/test_flow_invite_to_access.py
  tests/test_login_web.py
  tests/test_scheduled_tasks.py
  tests/test_user_confirm_invites_and_register.py
Labels: must have

#1158 Add unit tests for scheduled_tasks.py functions
  CHANGELOG.md
  tests/conftest.py
  tests/test_scheduled_tasks.py
Labels: tests, must have
