Repository ScilifelabDataCentre/dds_web, pull requests merged in 2022-03, with the labels that each got.

#960 ADR update
  ADR.md
Labels: documentation

#943 Relax username requirements a little
  CHANGELOG.md
  dds_web/api/schemas/user_schemas.py
  dds_web/forms.py
  dds_web/utils.py
Labels: could have

#958 Action log entry for uncaught exceptions.
  CHANGELOG.md
  dds_web/api/dds_decorators.py
Labels: must have

#963 Fix mailing note
  CHANGELOG.md
  dds_web/api/user.py
Labels: bug, must have

#971 Bugs fixed
  ADR.md
  CHANGELOG.md
  dds_web/api/dds_decorators.py
  dds_web/api/project.py
  dds_web/api/schemas/project_schemas.py
  dds_web/api/schemas/user_schemas.py
  dds_web/api/user.py
  dds_web/forms.py
  dds_web/templates/mail/project_release.html
  dds_web/templates/mail/project_release.txt
  dds_web/utils.py
Labels: bug, must have

#974 Return role when listing project users
  CHANGELOG.md
  dds_web/api/project.py
  tests/test_project_listing.py
Labels: Suggestion, could have

#975 Custom registration form error messages
  CHANGELOG.md
  dds_web/forms.py
  dds_web/templates/user/register.html
  dds_web/web/user.py
Labels: bug

#987 After password reset: Only list projects when not superadmin
  dds_web/templates/user/password_reset_completed.html
  dds_web/web/user.py
Labels: bug, must have

#991 Add check for if superadmin for delete email
  dds_web/api/user.py
Labels: bug

#989 Fix formatting and error messages
  CHANGELOG.md
  dds_web/__init__.py
  dds_web/api/project.py
  dds_web/api/user.py
  dds_web/config.py
  dds_web/forms.py
  dds_web/templates/mail/deletion_request.html
  dds_web/templates/mail/deletion_request.txt
  dds_web/templates/user/password_reset_completed.html
  dds_web/templates/user/register.html
  dds_web/web/user.py
  tests/test_project_status.py
Labels: bug

#993 Simplify setting up dev environment
  CHANGELOG.md
  Dockerfiles/cli.Dockerfile
  README.md
  dds_web/config.py
  docker-compose.yml
Labels: should have

#994 Run pip install before injecting into the container
  README.md
  docker-compose.yml
Labels: backend, could have

#916 WIP: Start bringing back the front-end
  Dockerfiles/nodebuilder.Dockerfile
  README.md
  dds_web/__init__.py
  dds_web/static/img/favicon.png
  dds_web/static/img/scilifelab_symbol.svg
  dds_web/static/js/dds.js
  dds_web/static/package-lock.json
  dds_web/static/package.json
  dds_web/static/robots.txt
  dds_web/static/scss/_custom.scss
  dds_web/static/scss/_homepage.scss
  dds_web/static/scss/_variables.scss
  dds_web/static/scss/dds_auto.scss
  dds_web/static/scss/dds_dark.scss
  dds_web/static/scss/dds_light.scss
  dds_web/templates/404.html
  dds_web/templates/base.html
  dds_web/templates/components/hero_image.svg
  dds_web/templates/components/login_form.html
  dds_web/templates/error.html
  dds_web/templates/home.html
  dds_web/templates/index.html
  dds_web/templates/navbar.html
  dds_web/templates/user/account.html
  dds_web/templates/user/change_password.html
  dds_web/templates/user/confirm2fa.html
  dds_web/templates/user/login.html
  dds_web/templates/user/logout.html
  dds_web/templates/user/password_reset_completed.html
  dds_web/templates/user/register.html
  dds_web/templates/user/request_reset_password.html
  dds_web/templates/user/reset_password.html
  dds_web/templates/user/userbase.html
  dds_web/templates/user/userdeleted.html
  dds_web/templates/user/userexists.html
  dds_web/web/root.py
  dds_web/web/user.py
  docker-compose.yml
  requirements.txt
  tests/conftest.py
  tests/docker-compose-test-interactive.yml
  tests/test_login_web.py
  tests/test_user_confirm_invites_and_register.py
  tests/test_user_reset_password.py
Labels: web-interface, must have

#1010 Prettier code
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker-compose-tests.yml
  .github/workflows/prettier.yml
  .github/workflows/python-black.yml
  .prettierignore
  .prettierrc.yaml
  ADR.md
  CHANGELOG.md
  README.md
  dds_web/static/js/dds.js
  dds_web/static/scss/_custom.scss
  dds_web/static/scss/_homepage.scss
  dds_web/static/scss/_variables.scss
  dds_web/static/scss/dds_auto.scss
  dds_web/static/scss/dds_dark.scss
  dds_web/static/scss/dds_light.scss
  dds_web/templates/navbar.html
  docker-compose.yml
  run_dir/sensitive/.empty
  run_dir/sensitive/s3_config_example.json
  tests/docker-compose-test-interactive.yml
  tests/docker-compose-test.yml
Labels: enhancement, could have

#1013 Fix the dark mode switch behaviour
  dds_web/static/js/dds.js
  dds_web/static/scss/dds_dark.scss
  dds_web/templates/base.html
Labels: web-interface, should have

#1016 Forbid superadmin from creating project
  dds_web/api/project.py
Labels: must have

#1017 Delete bucket
  dds_web/api/api_s3_connector.py
  dds_web/api/project.py
Labels: bug, must have

#1019 change delete_folder regex
  dds_web/api/files.py
Labels: bug, must have

#1020 Rewite login page to use component, nicer HTML styling.
  dds_web/forms.py
  dds_web/templates/components/login_form.html
  dds_web/templates/home.html
  dds_web/templates/user/login.html
  dds_web/web/root.py
Labels: should have

#1023 Size column
  CHANGELOG.md
  dds_web/api/project.py
Labels: must have

#1026 clarify in user activation
  dds_web/api/user.py
  tests/test_flow_invite_to_access.py
  tests/test_project_access.py
  tests/test_project_user_keys.py
  tests/test_user_activation.py
  tests/test_user_delete.py
  tests/test_user_info.py
Labels: must have

#1039 AddUser: Specific error message for unit users
  CHANGELOG.md
  dds_web/api/user.py
Labels: should have

#1041 Improve messages, hide size from Researchers, disallow characters and fix regex
  CHANGELOG.md
  dds_web/api/api_s3_connector.py
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/api/schemas/project_schemas.py
  dds_web/api/user.py
  dds_web/forms.py
  dds_web/static/js/dds.js
  dds_web/static/scss/dds_dark.scss
  dds_web/templates/base.html
  dds_web/templates/components/login_form.html
  dds_web/templates/home.html
  dds_web/templates/user/login.html
  dds_web/utils.py
  dds_web/web/root.py
  tests/test_flow_invite_to_access.py
  tests/test_project_access.py
  tests/test_project_user_keys.py
  tests/test_user_activation.py
  tests/test_user_delete.py
  tests/test_user_info.py
Labels: must have

#1034 Rate limit: Error message
  CHANGELOG.md
  dds_web/templates/error.html
  dds_web/web/user.py
Labels: must have

#1050 Add new endpoint for listing unit users
  CHANGELOG.md
  dds_web/api/__init__.py
  dds_web/api/user.py
  tests/__init__.py
  tests/test_users_list.py
Labels: must have

#1054 make hotp invalid after password reset
  CHANGELOG.md
  dds_web/database/models.py
  dds_web/web/user.py
Labels: must have

#1055 Fix crash when uploading
  dds_web/api/project.py
  dds_web/api/s3.py
  tests/test_project_status.py
Labels: bug, must have

#1059 List unit users as Super Admin
  CHANGELOG.md
  dds_web/api/user.py
  tests/test_users_list.py
Labels: must have

#1060 Get unit info as Super Admin
  CHANGELOG.md
  dds_web/api/__init__.py
  dds_web/api/dds_decorators.py
  dds_web/api/unit.py
  dds_web/api/user.py
  dds_web/security/auth.py
  tests/__init__.py
  tests/test_unit_list.py
  tests/test_users_list.py
Labels: must have

#1063 Fix deadline option
  dds_web/api/project.py
  tests/test_project_status.py
Labels: must have

#1066 Require 2 unit admins and recommend 3
  dds_web/api/project.py
  dds_web/api/user.py
  dds_web/utils.py
  tests/test_project_creation.py
  tests/test_project_status.py
  tests/test_user_remove_association.py
Labels: must have

#1070 Change list files to return int instead of str
  CHANGELOG.md
  dds_web/api/files.py
  dds_web/api/project.py
  dds_web/utils.py
Labels: should have

#1067 Batch deleting of 1000 entries at a time
  CHANGELOG.md
  dds_web/api/api_s3_connector.py
  dds_web/api/files.py
Labels: must have

#1058 Password reset tracking
  CHANGELOG.md
  dds_web/database/models.py
  dds_web/security/auth.py
  dds_web/web/user.py
  docker-compose.yml
  migrations/versions/1256117ad629_add_password_reset.py
  tests/test_user_reset_password.py
Labels: must have

#1073 update adr
  ADR.md
  dds_web/api/api_s3_connector.py
Labels: documentation

#1076 Flask command to create new unit
  CHANGELOG.md
  dds_web/__init__.py
Labels: must have

#1075 Add check to delete user
  CHANGELOG.md
  dds_web/api/user.py
  tests/test_user_delete.py
Labels: must have

#1077 Catch unexpected sql errors
  dds_web/api/dds_decorators.py
  dds_web/api/project.py
  dds_web/api/user.py
  dds_web/web/user.py
Labels: must have

#1081 remove try except because not working
  CHANGELOG.md
  dds_web/api/project.py
Labels: should have

#1078 Add flask command for uploading file upload error log
  dds_web/__init__.py
Labels: must have

#1085 fix bug in flask command
  dds_web/__init__.py
Labels: bug

#1087 Remove banner on the homepage about testing
  dds_web/templates/home.html
Labels: must have

#1088 Change 'the user does not' to 'you do not' (tester feedback)
  dds_web/errors.py
  tests/test_user_add.py
Labels: documentation, could have

#1089 Add catch of OperationalError in `files.py`
  CHANGELOG.md
  dds_web/api/files.py
Labels: database, must have

#1092 Catch operationalerror in s3.py
  dds_web/api/dds_decorators.py
  dds_web/api/s3.py
Labels: backend, database, must have

#1084 Validation
  CHANGELOG.md
  dds_web/api/project.py
  dds_web/api/schemas/project_schemas.py
  dds_web/development/db_init.py
  tests/test_project_creation.py
  tests/test_project_status.py
Labels: should have

#1094 Catch sqlalchemy.exc.OperationalError in user
  dds_web/api/user.py
Labels: must have

#1096 Better front-end styling for 2fa confirm page
  dds_web/forms.py
  dds_web/templates/user/confirm2fa.html
Labels: web-interface, should have

#1101 Styled several forms - password reset etc.
  dds_web/templates/user/change_password.html
  dds_web/templates/user/confirm2fa.html
  dds_web/templates/user/logout.html
  dds_web/templates/user/password_reset_completed.html
  dds_web/templates/user/request_reset_password.html
  dds_web/templates/user/reset_password.html
Labels: web-interface

#1097 Add Gitpod
  .gitpod.yml
  .vscode/settings.json
Labels: could have

#1102 Minor style improvements to 2fa email
  dds_web/templates/mail/authenticate.html
Labels: web-interface

#1103 Tidy user profile page
  dds_web/__init__.py
  dds_web/templates/user/account.html
  dds_web/web/user.py
Labels: web-interface

#1040 Migrations without model
  CHANGELOG.md
  migrations/versions/666003748d14_change_active_nullable_and_default.py
  migrations/versions/a5a40d843415_changed_sensitive.py
  migrations/versions/d117e6299dc9_remove_project_invites.py
Labels: must have

#1110 Project Access Reset and Send Email
  CHANGELOG.md
  dds_web/templates/mail/project_access_reset.html
  dds_web/templates/mail/project_access_reset.txt
  dds_web/utils.py
  dds_web/web/user.py
  tests/test_user_reset_password.py
Labels: must have
